/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/tower/radiotower.glb --printwidth 120 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/radiotower.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BezierCircle.geometry}
        material={nodes.BezierCircle.material}
        position={[-0.043, -0.256, -0.33]}
        scale={-0.012}
      />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.001']} position={[-0.014, 0.389, -0.335]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['1480250348_telecommunication_tower']} />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-0.023, 0.447, -0.309]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[-0.023, 0.423, -0.309]}
      />
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-0.041, 0, 0]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[-0.001, 0, -0.003]} />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.001']}
        position={[-0.052, -0.382, -0.33]}
        scale={[1, 1, 0.619]}
      />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.001']} position={[-0.041, 0, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[-0.041, 0, 0]} />
      <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['1480250348_telecommunication_tower']} />
      <mesh geometry={nodes.Cylinder005_2.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/radiotower.glb')
